### ISSUE TITLE
Mutable.ai makes vs code too slow

### ISSUE THREAD

**Issue by hariprasadiit** [mutableai/public#2] opened 2022-09-04 13:12 UTC
Hello,

It's nice product, but the extension is making vs code too slow to use. If I disable this extension, vs code is back to how it was.

**Comment by yitao-mutable** [comment] 2022-09-06 18:02
Hi, thanks for your feedback. We are constantly improving our product.

Can you try the following:
Disable other extensions
Restart VS Code
Try switch between the release version and pre-release version
Disable the extension, then re-enable the extension and see if it truly makes a difference

Mainly because any extension that gives inline prompts could conflict with each other (VS Code added this feature to extensions recently and no way to prioritize one extension over the other)

If you still experience an issue, can you please send a screenshot or screen recording of RAM or CPU usage before and after installing the extension? That would really help us debug any potential issues.

Thanks

**Comment by yitao-mutable** [comment] 2022-09-23 16:52
After extensive testing on Windows, Debian, Ubuntu, and Mac, we couldn't reproduce any slowdown issues. Closing this for now.

**Closed by yitao-mutable** 2022-09-23 16:52 UTC
